# Default values for rhoai-environment-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

dataScienceProjectDisplayName: RHOAI Playground
dataScienceProjectNamespace: rhoai-playground

# workbench:
#   name: notebook-gpu
#   displayName: Notebook GPU
#   namespace: rhoai-playground
#   image: pytorch:2024.2
#   resources:
#     limits:
#       cpu: '2'
#       memory: 8Gi
#       nvidiaGpu: '1'
#     requests:
#       cpu: '1'
#       memory: 6Gi
#       nvidiaGpu: '1'

workbench:
  name: notebook
  displayName: Notebook
  namespace: rhoai-playground
  image: pytorch:2024.2
  resources:
    limits:
      cpu: '3'
      memory: 10Gi
    requests:
      cpu: '1'
      memory: 6Gi

# Example with Minio
pipelinesConnection:
  storageBackend: minio
  secretName: dspa-pipelines-connection-secret
  type: s3
  scheme: http
  awsS3Endpoint: minio-service.ic-shared-minio.svc.cluster.local
  awsS3Port: "9000"

distributedWorkloads:
  enabled: true

# # Example with ODF
# pipelinesConnection:
#   storageBackend: odf
#   secretName: dspa-pipelines-connection-secret
#   type: s3
#   scheme: https
#   awsS3Endpoint: s3.openshift-storage.svc
#   awsS3Port: "443"

# # Example with AWS
# pipelinesConnection:
#   storageBackend: aws
#   secretName: dspa-pipelines-connection-secret
#   displayName: pipelines
#   type: s3
#   scheme: https
#   awsAccessKeyId: AWS_ACCESS_KEY_ID
#   awsSecretAccessKey: AWS_SECRET_ACCESS_KEY
#   awsDefaultRegion: eu-west-1
#   awsS3Endpoint: s3.eu-west-1.amazonaws.com
