# Default values for rhoai-environment-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

dataScienceProjectDisplayName: RHOAI Playground
dataScienceProjectNamespace: rhoai-playground

workbench:
  name: notebook-gpu
  displayName: Notebook GPU
  namespace: rhoai-playground
  image: pytorch:2024.1
  resources:
    limits:
      cpu: '2'
      memory: 8Gi
      nvidiaGpu: '1'
    requests:
      cpu: '1'
      memory: 6Gi
      nvidiaGpu: '1'

# workbench:
#   name: notebook
#   displayName: Notebook
#   namespace: rhoai-playground
#   image: pytorch:2024.1
#   resources:
#     limits:
#       cpu: '2'
#       memory: 8Gi
#     requests:
#       cpu: '1'
#       memory: 6Gi

pipelinesConnection:
  storageBackendODF: true
  secretName: rhoai-connection-pipelines
  type: s3
  scheme: https
  awsDefaultRegion: odf
  awsS3Bucket: odf-connection-pipelines-64375d16-d0a9-4403-82e0-fd05d984d209
  awsS3Endpoint: s3.openshift-storage.svc
  awsS3Port: "443"

# # Old example using AWS
# pipelinesConnection:
#   secretName: aws-connection-pipelines
#   displayName: pipelines
#   type: s3
#   scheme: https
#   awsAccessKeyId: AWS_ACCESS_KEY_ID
#   awsSecretAccessKey: AWS_SECRET_ACCESS_KEY
#   awsDefaultRegion: eu-west-1
#   awsS3Bucket: rhoai-playground-pipelines
#   awsS3Endpoint: s3.eu-west-1.amazonaws.com
