---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-kueue-operator
  namespace: openshift-kueue-operator
  annotations:
    argocd.argoproj.io/sync-wave: "-05"
spec:
  upgradeStrategy: Default