---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: kueue-operator
  namespace: openshift-kueue-operator
  annotations:
    argocd.argoproj.io/sync-wave: "-05"
spec:
  channel: stable-v1.1
  installPlanApproval: Manual
  name: kueue-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
