---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - operator/
  - clusterpolicy-gpu-cluster-policy.yaml
  - cm-device-plugin-config.yaml # Time Slicing

configMapGenerator:
  - name: nvidia-dcgm-exporter-dashboard
    namespace: openshift-config-managed
    files:
      - dcgm-exporter-dashboard.json
    options:
      disableNameSuffixHash: true
      labels:
        console.openshift.io/dashboard: 'true'
        console.openshift.io/odc-dashboard: 'true'
