---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nvidia-gpu-operator

resources:
  - ns-nvidia-gpu-operator.yaml
  - og-nvidia-gpu-operator-group.yaml
  - sub-gpu-operator-certified.yaml
  - clusterpolicy-gpu-cluster-policy.yaml
  # - cm-device-plugin-config.yaml # Time Slicing

configMapGenerator:
  - name: nvidia-dcgm-exporter-dashboard
    namespace: openshift-config-managed
    files:
      - dcgm-exporter-dashboard.json
    options:
      disableNameSuffixHash: true
      labels:
        console.openshift.io/dashboard: 'true'
        console.openshift.io/odc-dashboard: 'true'

# Deploy HashiCorp Vault CSI driver
helmCharts:
- name: console-plugin-nvidia-gpu
  releaseName: console-plugin-nvidia-gpu
  repo: https://rh-ecosystem-edge.github.io/console-plugin-nvidia-gpu
  # valuesFile: values.yaml
  version: 0.2.5
  namespace: nvidia-gpu-operator
