---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rhods-admin-cluster-reader
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: rhods-admins
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-reader
