---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rhods-admin-mistral-7b
  namespace: mistral-7b
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: rhods-admins
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
