{{- if .Values.llmInferenceService.apiKey }}
---
kind: Secret
apiVersion: v1
metadata:
  name: openai-api-key
  namespace: {{ .Release.Namespace }}
stringData:
  OPENAI_API_KEY: "{{ .Values.llmInferenceService.apiKey }}"
type: Opaque
{{- end }}
