---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: servicemeshoperator
  namespace: openshift-operators
  annotations:
    argocd.argoproj.io/sync-wave: "-05"
spec:
  channel: stable
  installPlanApproval: Automatic
  name: servicemeshoperator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  # config:
  #   nodeSelector: 
  #     node-role.kubernetes.io/infra: ""
  #   tolerations: 
  #   - effect: NoSchedule
  #     key: node-role.kubernetes.io/infra
  #     value: reserved
  #   - effect: NoExecute
  #     key: node-role.kubernetes.io/infra
  #     value: reserved
