{
 "title": "DNS Operator",
 "description": "Dashboard for use with the DNS Operator in the kuadrant project: https://github.com/Kuadrant/dns-operator",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Health Check Probes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of active probes",
   "type": "gauge",
   "gridPos": { "h": 16, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kuadrant_dnshealthcheckprobe_healthy_status == 1)",
     "legendFormat": "healthy"
    },
    {
     "expr": "count(kuadrant_dnshealthcheckprobe_healthy_status != 1) or vector(0)",
     "legendFormat": "unhealthy"
    },
    {
     "expr": "count(kuadrant_dnshealthcheckprobe_healthy_status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Probe request rate by response code (req/s)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 21, "x": 3, "y": 1 },
   "targets": [
    {
     "expr": "sum by (client, code) (rate(http_client_requests_total{client=\"probe\"}[15m]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Probe latency (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 21, "x": 3, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(http_client_request_latency_seconds_bucket{client=\"probe\",code=\"200\"}[15m])))",
     "legendFormat": "99%ile"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_client_request_latency_seconds_bucket{client=\"probe\",code=\"200\"}[15m])))",
     "legendFormat": "95%ile"
    }
   ]
  },
  { "title": "DNS Provider", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Provider latency (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, client) (rate(http_client_request_latency_seconds_bucket{client=~\"aws|gcp|azure\",code=\"200\"}[15m])))",
     "legendFormat": "{{client}}:99%ile"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, client) (rate(http_client_request_latency_seconds_bucket{client=~\"aws|gcp|azure\",code=\"200\"}[15m])))",
     "legendFormat": "{{client}}:95%ile"
    }
   ]
  },
  {
   "title": "Provider request rate by response code (req/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum by (client, code) (rate(http_client_requests_total{client=~\"aws|gcp|azure\"}[15m]))",
     "legendFormat": "{{client}}:{{code}}"
    }
   ]
  }
 ]
}