{{- if .Values.evalHub.enabled }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.evalHub.namespace }}
  labels:
    evalhub.trustyai.opendatahub.io/tenant: ""  # Register as EvalHub tenant namespace
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
{{- end }}
