{{ if .Values.llm_d.enabled }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: maas-default-gateway
  namespace: openshift-ingress
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "10"
    networking.istio.io/service-type: ClusterIP
spec:
  gatewayClassName: maas-default-gateway
  # Use ConfigMap to inject Service CA annotation for automatic TLS certificate generation
  infrastructure:
    parametersRef:
      group: ""
      kind: ConfigMap
      name: maas-service-override
  listeners:
    # External listener - HTTPS for Route traffic (public hostname)
    - allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchExpressions:
              - key: rhoai-serving/model
                operator: Exists
      hostname: maas.apps.{{ .Values.global.clusterDomain }}
      name: external
      port: 443
      protocol: HTTPS
      tls:
        certificateRefs:
          - group: ""
            kind: Secret
            name: {{ if and .Values.llm_d.tlsCrtB64 .Values.llm_d.tlsKeyB64 }}maas-default-gateway-external-certs{{ else }}maas-default-gateway-internal-certs{{ end }}
        mode: Terminate
    # Internal listener - HTTPS for Service traffic (internal cluster access)
    - allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchExpressions:
              - key: rhoai-serving/model
                operator: Exists
      hostname: maas-default-gateway-maas-default-gateway.openshift-ingress.svc.cluster.local
      name: internal
      port: 443
      protocol: HTTPS
      tls:
        certificateRefs:
          - group: ""
            kind: Secret
            name: maas-default-gateway-internal-certs
        mode: Terminate
{{ end }}
