---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app: rhoai-dependencies
  name: rhoai-dependencies
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: rhoai-dependencies
    repoURL: https://github.com/alvarolop/rhoai-gitops.git
    targetRevision: main
    kustomize:
      patches:
        - target:
            kind: NodeFeatureDiscovery
            name: nfd-instance
          patch: |-
            - op: replace
              path: /spec/operand/image
              value: registry.redhat.io/openshift4/ose-node-feature-discovery-rhel9:v4.17
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions: []
