---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app: ocp-odf
  name: ocp-odf
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: ocp-odf
    repoURL: https://github.com/alvarolop/rhoai-gitops.git
    targetRevision: main
    kustomize:
      # patches:
      #   - target:
      #       kind: Subscription
      #       name: odf-operator
      #     patch: |-
      #       - op: replace
      #         path: /spec/channel
      #         value: stable-4.17
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions: []
