---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app: milvus
  name: milvus
  namespace: gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: components/milvus
    repoURL: https://github.com/alvarolop/rhoai-gitops.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    # syncOptions:
    #   - CreateNamespace=true
