---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app: rhoai-dependencies
  name: rhoai-dependencies
  namespace: gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: rhoai-dependencies
    repoURL: https://github.com/alvarolop/rhoai-gitops.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions: []
