---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app: serve-vllm-mistral-7b
  name: serve-vllm-mistral-7b
  namespace: gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: gitops/model
    repoURL: https://github.com/alvarolop/model-serving-utils.git
    targetRevision: main
    helm:
      values: |
        model:
          accelerator:
            productName: NVIDIA-A10G-SHARED
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
