---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app: minio
  name: minio
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ic-shared-minio
  project: default
  source:
    path: components/minio
    repoURL: https://github.com/alvarolop/rhoai-gitops.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
