---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app: serve-granite-1b-a400m
  name: serve-granite-1b-a400m
  namespace: gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: gitops/model
    repoURL: https://github.com/alvarolop/model-serving-utils.git
    targetRevision: main
    helm:
      values: |
        dataScienceProjectDisplayName: granite-1b-a400m
        dataScienceProjectNamespace: granite-1b-a400m
        instanceName: granite-1b-a400m
        model:
          root: ibm-granite
          id: granite-3.1-1b-a400m-base
          name: granite-1b-a400m
          displayName: "Granite 3B A800m Base"
          additionalLabels:
            networking.knative.dev/visibility: cluster-local
          # https://docs.vllm.ai/en/latest/features/tool_calling.html#ibm-granite
          # chatTemplate: /apps/data/template/tool_chat_template_granite.jinja
          toolCallParser: granite
          maxModelLen: "4096"
          runtime: 
            resources:
              limits:
                cpu: '8'
                memory: 16Gi
              requests:
                cpu: '4'
                memory: 8Gi
            image: quay.io/modh/vllm@sha256:c86ff1e89c86bc9821b75d7f2bbc170b3c13e3ccf538bf543b1110f23e056316
          accelerator:
            productName: NVIDIA-A10G-SHARED
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
