---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app: lls-playground
  name: lls-playground
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: components/lls-playground
    repoURL: https://github.com/alvarolop/rhoai-gitops.git
    targetRevision: main
    helm:
      values: |
        global:
          clusterDomain: $CLUSTER_DOMAIN
        llamaStack:
          endpoint: $LLS_ENDPOINT
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
