---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app: openshift-lightspeed
  name: openshift-lightspeed
  namespace: gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: components/openshift-lightspeed
    repoURL: https://github.com/alvarolop/rhoai-gitops.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
