---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - modelregistry-default.yaml
  # - modelregistry-dev.yaml
  # - modelregistry-pre.yaml
  # - modelregistry-pro.yaml
  - secret-model-registry-db.yaml
