{{- if and .Values.evalHub.enabled .Values.evalHub.postgresql.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.evalHub.postgresql.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
{{- end }}
