{{- if and .Values.evalHub.enabled .Values.evalHub.postgresql.enabled }}
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.evalHub.postgresql.name }}-credentials
  namespace: {{ .Values.evalHub.postgresql.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
stringData:
  POSTGRES_DB: {{ .Values.evalHub.postgresql.connection.database | quote }}
  POSTGRES_USER: {{ .Values.evalHub.postgresql.connection.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.evalHub.postgresql.connection.password | quote }}
type: Opaque
{{- end }}
