---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: servicemesh-operator
  namespace: openshift-operators
  annotations:
    argocd.argoproj.io/sync-wave: "-05"
spec:
  channel: stable
  installPlanApproval: Automatic
  name: servicemeshoperator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
