---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kuadrant-system
resources:
  - sa-enable-plugin.yaml
  - cr-enable-plugin.yaml
  - crb-enable-plugin.yaml
  - job-enable-plugin.yaml
