{{- if and .Values.featureStore.enabled .Values.featureStore.example.enabled }}
---
apiVersion: feast.dev/v1
kind: FeatureStore
metadata:
  name: {{ .Values.featureStore.example.name }}
  namespace: {{ .Values.featureStore.example.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  labels:
    feature-store-ui: enabled
spec:
  feastProject: {{ .Values.featureStore.example.name }}
  feastProjectDir:
    git:
      url: {{ .Values.featureStore.example.feastProjectDir.git.url }}
      ref: {{ .Values.featureStore.example.feastProjectDir.git.ref }}
{{- if .Values.featureStore.example.authz.enabled }}
  authz:
    type: Kubernetes
{{- end }}
  services:
    offlineStore:
      server:
        logLevel: debug
    onlineStore:
      server:
        logLevel: debug
    registry:
      local:
        server:
          restAPI: false
    ui: {}
{{- end }}