{{- if $.Values.featureStore.enabled }}
{{- range $.Values.featureStore.examples }}
{{- if .enabled }}
---
apiVersion: feast.dev/v1
kind: FeatureStore
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  labels:
    feature-store-ui: enabled
spec:
  feastProject: {{ .name }}
  feastProjectDir:
    git:
{{ .feastProjectDir.git | toYaml | indent 6 }}
{{- if .authz.enabled }}
  authz:
    type: Kubernetes
{{- end }}
  services:
    offlineStore:
      server:
        logLevel: debug
    onlineStore:
      server:
        logLevel: debug
    registry:
      local:
        server:
          restAPI: false
    ui: {}
{{- end }}
{{- end }}
{{- end }}
