{{- if $.Values.featureStore.enabled }}
{{- range $.Values.featureStore.examples }}
{{- if .enabled }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .namespace }}
  labels:
    opendatahub.io/dashboard: 'true'
{{- end }}
{{- end }}
{{- end }}
