{{- if $.Values.featureStore.enabled }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $.Values.featureStore.namespace }}
  annotations:
    openshift.io/description: "RHOAI - Feature Store"
    openshift.io/display-name: "Feature Store Namespace"
  labels:
    opendatahub.io/dashboard: 'true'
{{- end }}
