{{- if $.Values.featureStore.enabled }}
{{- range $.Values.featureStore.examples }}
{{- if and .enabled (dig "persistence" "offline" "size" "" .) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: feast-{{ .name }}-offline
  namespace: {{ .namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: Replace=true
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .persistence.offline.size }}
{{- end }}
{{- end }}
{{- end }}
