{{- if and .Values.featureStore.enabled .Values.featureStore.example.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: feast-{{ .Values.featureStore.example.name }}-offline
  namespace: {{ .Values.featureStore.example.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: Replace=true
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.featureStore.example.persistence.offline.size }}
{{- end }}
