---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: kuadrant-system
  namespace: kuadrant-system
  annotations:
    argocd.argoproj.io/sync-wave: "-05"
spec:
  upgradeStrategy: Default