{{ if and .Values.llm_d.enabled .Values.llm_d.ocpRouteGateway.enabled }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: openshift-ai-inference
  namespace: openshift-ingress
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  host: openshift-ai-inference.apps.{{ .Values.global.clusterDomain }}
  port:
    targetPort: external
  to:
    kind: Service
    name: openshift-ai-inference-openshift-ai-inference
    weight: 100
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
{{ end }}
