---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-distributed-tracing
  namespace: openshift-distributed-tracing
  annotations:
    argocd.argoproj.io/sync-wave: "-05"
spec:
  upgradeStrategy: Default
