---
apiVersion: datasciencecluster.opendatahub.io/v1
kind: DataScienceCluster
metadata:
  name: default-dsc
  labels:
    app.kubernetes.io/name: datasciencecluster
    app.kubernetes.io/part-of: rhods-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: rhods-operator
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  components:
    dashboard:
      managementState: Managed
    aipipelines:
      argoWorkflowsControllers:
        managementState: Managed
      managementState: Managed
    feastoperator:
      managementState: {{ if .Values.featureStore.enabled }}Managed{{ else }}Removed{{ end }}
    kserve:
      nim:
        managementState: Managed
      rawDeploymentServiceConfig: Headless
      serving:
        ingressGateway:
          certificate:
            type: OpenshiftDefaultIngress
        managementState: Managed
        name: knative-serving
      managementState: Managed
    kueue:
      defaultClusterQueueName: default
      defaultLocalQueueName: default
      managementState: {{ if .Values.distributedWorkloads.enabled }}Unmanaged{{ else }}Removed{{ end }}
    llamastackoperator:
      managementState: {{ if .Values.llamaStack.enabled }}Managed{{ else }}Removed{{ end }}
    modelregistry:
      managementState: {{ if .Values.modelRegistry.enabled }}Managed{{ else }}Removed{{ end }}
      registriesNamespace: rhoai-model-registries
    ray:
      managementState: Managed
    workbenches:
      workbenchNamespace: rhods-notebooks
      managementState: Managed
    # Kubeflow Training Operator to tune models
    trainingoperator:
      managementState: Managed
    trustyai:
      managementState: Managed
