---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/instance: rhoai

resources:
  - operator-pipelines
  - operator-serverless
  - operator-servicemesh
  # - operator-authorino
  - operator-rhoai
  - operator-nfd
  - operator-nvidia-gpu
