---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/instance: rhoai

resources:
  # Actual installation of RHOAI operator
  - operator-rhoai
  
  - rhoai-configuration # Configure RHOAI cluster
  # - rhoai-custom-notebooks # Create Custom Notebooks
  # - rhoai-runtimes

helmGlobals:
  chartHome: .

helmCharts:
- name: rhoai-environment-chart
  includeCRDs: false
  releaseName: rhoai-playground
  version: 0.1.0
