---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/instance: rhoai

resources:
  - operator-rhoai
  
  - rhoai-configuration # Configure RHOAI cluster

  - distributed-workloads
  # - rhoai-custom-notebooks # Create Custom Notebooks
  # - rhoai-runtimes

# helmGlobals:
#   chartHome: .

# helmCharts:
# - name: rhoai-environment-chart
#   includeCRDs: false
#   releaseName: rhoai-playground
#   version: 0.1.0
