---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/instance: rhoai

resources:

  # Support for GPU Acceleration
  - operator-nfd
  - operator-nvidia-gpu

  # KServe Installation for Single-model server
  - operator-serverless
  - operator-jaeger
  # - operator-grafana-tempo
  # - operator-opentelemetry
  - operator-kiali
  - operator-servicemesh
  
  # Support for authentication of server models
  # - operator-authorino

  # Actual installation of RHOAI operator
  - operator-rhoai
