---
apiVersion: ols.openshift.io/v1alpha1
kind: OLSConfig
metadata:
  name: cluster
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  llm:
    providers:
      - name: Mistral
        type: openai
        # credentialsSecretRef:
        #   name: credentials
        url: https://mistral-7b.mistral-7b.svc.cluster.local/v1
        models:
          - name: mistral-7b
      # - name: myOpenai
      #   type: openai
      #   credentialsSecretRef:
      #     name: credentials
      #   url: https://api.openai.com/v1
      #   models:
      #     - name: gpt-3.5-turbo
  ols:
    defaultModel: mistral-7b
    defaultProvider: Mistral