---
apiVersion: ols.openshift.io/v1alpha1
kind: OLSConfig
metadata:
  name: cluster
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  llm:
    providers:
      - name: red_hat_openshift_ai
        type: rhoai_vllm
        credentialsSecretRef:
          name: credentials-mistral
        url: "https://mistral-7b.mistral-7b.svc.cluster.local:443/v1"
        models:
          - name: mistral-7b
      # - name: myOpenai
      #   type: openai
      #   credentialsSecretRef:
      #     name: credentials
      #   url: https://api.openai.com/v1
      #   models:
      #     - name: gpt-3.5-turbo
  ols:
    defaultModel: mistral-7b
    defaultProvider: red_hat_openshift_ai
    additionalCAConfigMapRef:
      name: openshift-service-ca.crt
