{{- if .Values.modelRegistry.enabled }}
---
kind: Secret
apiVersion: v1
metadata:
  name: model-registry-db
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  namespace: rhoai-model-registries
stringData:
  database-name: model_registry_db
  database-password: secure-root-password
  database-user: root
type: Opaque
{{- end }}
