{{- if and .Values.modelsAsService.enabled .Values.modelsAsService.postgresql.enabled }}
{{- $pg := .Values.modelsAsService.postgresql }}
{{- $host := printf "%s.%s.svc.cluster.local" $pg.name $pg.namespace }}
{{- $sslmode := ternary "require" "disable" $pg.service.ssl }}
---
apiVersion: v1
kind: Secret
metadata:
  name: maas-db-config
  namespace: redhat-ods-applications
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
  DB_CONNECTION_URL: {{ printf "postgresql://%s:%s@%s:%v/%s?sslmode=%s" ($pg.connection.user | urlquery) ($pg.connection.password | urlquery) $host $pg.service.port $pg.connection.database $sslmode | quote }}
{{- end }}
