---
apiVersion: template.openshift.io/v1
kind: Template
objects:

  - kind: Secret
    apiVersion: v1
    metadata:
      name: ${SECRET_NAME}
      namespace: ${NOTEBOOK_NAMESPACE}
      labels:
        opendatahub.io/dashboard: 'true'
        opendatahub.io/managed: 'true'
      annotations:
        opendatahub.io/connection-type: s3
        openshift.io/display-name: "AWS S3 - Pipelines"
    stringData:
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_DEFAULT_REGION: "${AWS_DEFAULT_REGION}"
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
      AWS_S3_ENDPOINT: ${AWS_S3_ENDPOINT}
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
    type: Opaque

parameters:
  - name: SECRET_NAME
    description: "The name of the secret."
    required: false
    value: aws-connection-pipelines
  - name: NOTEBOOK_NAMESPACE
    description: "The project where the notebook is deployed."
    required: true
  - name: AWS_ACCESS_KEY_ID
    description: "AWS access_key_id."
    required: true
  - name: AWS_SECRET_ACCESS_KEY
    description: "AWS access_key_secret."
    required: true
  - name: AWS_DEFAULT_REGION
    description: "AWS region."
    required: true
  - name: AWS_S3_BUCKET
    description: "S3 Bucket name."
    required: true
  - name: AWS_S3_ENDPOINT
    description: "S3 Endpoint."
    required: false
    value: https://s3.eu-west-1.amazonaws.com