# PIPELINE DEFINITION
# Name: hello-world-pipeline
# Inputs:
#    recipient: str
components:
  comp-create-hello-message:
    executorLabel: exec-create-hello-message
    inputDefinitions:
      parameters:
        name:
          parameterType: STRING
    outputDefinitions:
      parameters:
        Output:
          parameterType: STRING
  comp-say-hello:
    executorLabel: exec-say-hello
    inputDefinitions:
      parameters:
        message:
          parameterType: STRING
deploymentSpec:
  executors:
    exec-create-hello-message:
      container:
        args:
        - --executor_input
        - '{{$}}'
        - --function_to_execute
        - create_hello_message
        command:
        - sh
        - -c
        - "\nif ! [ -x \"$(command -v pip)\" ]; then\n    python3 -m ensurepip ||\
          \ python3 -m ensurepip --user || apt-get install python3-pip\nfi\n\nPIP_DISABLE_PIP_VERSION_CHECK=1\
          \ python3 -m pip install --quiet --no-warn-script-location 'kfp==2.11.0'\
          \ '--no-deps' 'typing-extensions>=3.7.4,<5; python_version<\"3.9\"' && \"\
          $0\" \"$@\"\n"
        - sh
        - -ec
        - 'program_path=$(mktemp -d)


          printf "%s" "$0" > "$program_path/ephemeral_component.py"

          _KFP_RUNTIME=true python3 -m kfp.dsl.executor_main                         --component_module_path                         "$program_path/ephemeral_component.py"                         "$@"

          '
        - "\nimport kfp\nfrom kfp import dsl\nfrom kfp.dsl import *\nfrom typing import\
          \ *\n\ndef create_hello_message(name: str) -> str:\n    \"\"\"Creates a\
          \ hello message.\"\"\"\n    hello_text = f'Hello, {name}!'\n    return hello_text\n\
          \n"
        image: python:3.9
    exec-say-hello:
      container:
        args:
        - --executor_input
        - '{{$}}'
        - --function_to_execute
        - say_hello
        command:
        - sh
        - -c
        - "\nif ! [ -x \"$(command -v pip)\" ]; then\n    python3 -m ensurepip ||\
          \ python3 -m ensurepip --user || apt-get install python3-pip\nfi\n\nPIP_DISABLE_PIP_VERSION_CHECK=1\
          \ python3 -m pip install --quiet --no-warn-script-location 'kfp==2.11.0'\
          \ '--no-deps' 'typing-extensions>=3.7.4,<5; python_version<\"3.9\"' && \"\
          $0\" \"$@\"\n"
        - sh
        - -ec
        - 'program_path=$(mktemp -d)


          printf "%s" "$0" > "$program_path/ephemeral_component.py"

          _KFP_RUNTIME=true python3 -m kfp.dsl.executor_main                         --component_module_path                         "$program_path/ephemeral_component.py"                         "$@"

          '
        - "\nimport kfp\nfrom kfp import dsl\nfrom kfp.dsl import *\nfrom typing import\
          \ *\n\ndef say_hello(message: str):\n    \"\"\"Prints the hello message.\"\
          \"\"\n    print(message)\n\n"
        image: python:3.9
pipelineInfo:
  name: hello-world-pipeline
root:
  dag:
    tasks:
      create-hello-message:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-create-hello-message
        inputs:
          parameters:
            name:
              componentInputParameter: recipient
        taskInfo:
          name: create-hello-message
      say-hello:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-say-hello
        dependentTasks:
        - create-hello-message
        inputs:
          parameters:
            message:
              taskOutputParameter:
                outputParameterKey: Output
                producerTask: create-hello-message
        taskInfo:
          name: say-hello
  inputDefinitions:
    parameters:
      recipient:
        parameterType: STRING
schemaVersion: 2.1.0
sdkVersion: kfp-2.11.0
