{{- if .Values.pipelines }}
---
apiVersion: datasciencepipelinesapplications.opendatahub.io/v1
kind: DataSciencePipelinesApplication
metadata:
  name: dspa
  namespace: {{ .Values.dataScienceProjectNamespace }}
  annotations:
    # argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "10"
spec:
  apiServer:
    artifactSignedURLExpirySeconds: 60
    caBundleFileMountPath: ''
    caBundleFileName: ''
    deploy: true
    enableOauth: true
    enableSamplePipeline: false
  database:
    disableHealthCheck: false
    mariaDB:
      deploy: true
      pipelineDBName: mlpipeline
      pvcSize: 10Gi
      username: mlpipeline
  dspVersion: v2
  objectStorage:
    disableHealthCheck: false
    enableExternalRoute: false
    externalStorage:
      basePath: ''
      bucket: {{ .Values.dataScienceProjectNamespace }}-{{ .Values.pipelines.secretName }}
      host: '{{ .Values.pipelines.awsS3Endpoint }}'
      port: '{{ .Values.pipelines.awsS3Port }}'
      region: '{{ .Values.pipelines.awsDefaultRegion | default "" }}'
      s3CredentialsSecret:
        accessKey: AWS_ACCESS_KEY_ID
        secretKey: AWS_SECRET_ACCESS_KEY
        secretName: "{{ .Values.pipelines.secretName }}"
      scheme: "{{ .Values.pipelines.scheme }}"
  persistenceAgent:
    deploy: true
    numWorkers: 2
  podToPodTLS: true
  scheduledWorkflow:
    cronScheduleTimezone: UTC
    deploy: true
{{- end }}
