---
apiVersion: kubeflow.org/v1
kind: Notebook
metadata:
  annotations:
    notebooks.opendatahub.io/inject-auth: "true"
    notebooks.opendatahub.io/last-image-selection: "{{ .Values.workbench.image }}"
    notebooks.opendatahub.io/last-size-selection: Small
    opendatahub.io/image-display-name: PyTorch
    {{- if or .Values.workbench.resources.requests.nvidiaGpu .Values.workbench.resources.limits.nvidiaGpu }}
    opendatahub.io/hardware-profile-name: default-profile
    opendatahub.io/hardware-profile-namespace: redhat-ods-applications
    openshift.io/description: This is an example Workbench using the PyTorch Image and a NVIDIA GPU
    {{- else }}
    openshift.io/description: This is an example Workbench using the PyTorch Image
    {{- end }}
    openshift.io/display-name: {{ .Values.workbench.name }}
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: {{ .Values.workbench.name }}
  namespace: {{ .Values.dataScienceProjectNamespace }}
  labels:
    app: {{ .Values.workbench.name }}
    opendatahub.io/dashboard: "true"
    opendatahub.io/odh-managed: "true"
spec:
  template:
    spec:
      affinity: {}
      containers:
      - env:
        - name: NOTEBOOK_ARGS
          value: |-
            --ServerApp.port=8888
            --ServerApp.token=''
            --ServerApp.password=''
            --ServerApp.base_url=/notebook/{{ .Values.dataScienceProjectNamespace }}/{{ .Values.workbench.name }}
            --ServerApp.quit_button=False
        - name: JUPYTER_IMAGE
          value: image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/{{ .Values.workbench.image }}
        - name: REQUESTS_CA_BUNDLE
          value: /etc/pki/tls/custom-certs/ca-bundle.crt
        - name: SSL_CERT_FILE
          value: /etc/pki/tls/custom-certs/ca-bundle.crt
        - name: PIPELINES_SSL_SA_CERTS
          value: /etc/pki/tls/custom-certs/ca-bundle.crt
        - name: KF_PIPELINES_SSL_SA_CERTS
          value: /etc/pki/tls/custom-certs/ca-bundle.crt
        - name: GIT_SSL_CAINFO
          value: /etc/pki/tls/custom-certs/ca-bundle.crt
        - name: PIP_CERT
          value: /etc/pki/tls/custom-certs/ca-bundle.crt
        image: image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/{{ .Values.workbench.image }}
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /notebook/{{ .Values.dataScienceProjectNamespace }}/{{ .Values.workbench.name }}/api
            port: notebook-port
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        name: {{ .Values.workbench.name }}
        ports:
        - containerPort: 8888
          name: notebook-port
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /notebook/{{ .Values.dataScienceProjectNamespace }}/{{ .Values.workbench.name }}/api
            port: notebook-port
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: '{{ .Values.workbench.resources.limits.cpu }}'
            memory: {{ .Values.workbench.resources.limits.memory }}
            {{- if .Values.workbench.resources.limits.nvidiaGpu }}
            nvidia.com/gpu: '{{ .Values.workbench.resources.requests.nvidiaGpu }}'
            {{- end }}
          requests:
            cpu: '{{ .Values.workbench.resources.requests.cpu }}'
            memory: {{ .Values.workbench.resources.requests.memory }}
            {{- if .Values.workbench.resources.requests.nvidiaGpu }}
            nvidia.com/gpu: '{{ .Values.workbench.resources.requests.nvidiaGpu }}'
            {{- end }}
        volumeMounts:
        - mountPath: /opt/app-root/src/
          name: {{ .Values.workbench.name }}-storage
        - mountPath: /dev/shm
          name: shm
        - mountPath: /etc/pki/tls/custom-certs/ca-bundle.crt
          name: trusted-ca
          readOnly: true
          subPath: ca-bundle.crt
        - mountPath: /opt/app-root/pipeline-runtimes/
          name: runtime-images
        - mountPath: /opt/app-root/runtimes	
          name: elyra-dsp-details
        workingDir: /opt/app-root/src
      # - args:
      #   - --secure-listen-address=0.0.0.0:8443
      #   - --upstream=http://127.0.0.1:8888/
      #   - --logtostderr=true
      #   - --v=10
      #   - --proxy-endpoints-port=8444
      #   - --config-file=/etc/kube-rbac-proxy/config-file.yaml
      #   - --tls-cert-file=/etc/tls/private/tls.crt
      #   - --tls-private-key-file=/etc/tls/private/tls.key
      #   - --auth-header-fields-enabled=true
      #   - --auth-header-user-field-name=X-Auth-Request-User
      #   - --auth-header-groups-field-name=X-Auth-Request-Groups
      #   image: registry.redhat.io/rhoai/odh-kube-auth-proxy-rhel9@sha256:1f4b2b9bb5061faf17299c2ae2405ab408e2b7ce349d9831eb6045990e6da005
      #   imagePullPolicy: Always
      #   livenessProbe:
      #     failureThreshold: 3
      #     httpGet:
      #       path: /healthz
      #       port: 8444
      #       scheme: HTTPS
      #     initialDelaySeconds: 30
      #     periodSeconds: 5
      #     successThreshold: 1
      #     timeoutSeconds: 1
      #   name: kube-rbac-proxy
      #   ports:
      #   - containerPort: 8443
      #     name: kube-rbac-proxy
      #     protocol: TCP
      #   readinessProbe:
      #     failureThreshold: 3
      #     httpGet:
      #       path: /healthz
      #       port: 8444
      #       scheme: HTTPS
      #     initialDelaySeconds: 5
      #     periodSeconds: 5
      #     successThreshold: 1
      #     timeoutSeconds: 1
      #   resources:
      #     limits:
      #       cpu: 100m
      #       memory: 64Mi
      #     requests:
      #       cpu: 100m
      #       memory: 64Mi
      #   volumeMounts:
      #   - mountPath: /etc/kube-rbac-proxy
      #     name: kube-rbac-proxy-config
      #   - mountPath: /etc/tls/private
      #     name: kube-rbac-proxy-tls-certificates
      enableServiceLinks: false
      serviceAccountName: {{ .Values.workbench.name }}
      {{- if or .Values.workbench.resources.requests.nvidiaGpu .Values.workbench.resources.limits.nvidiaGpu }}
      tolerations:
        - effect: NoSchedule
          key: nvidia.com/gpu
          operator: Exists
      {{- end }}
      volumes:
      - name: {{ .Values.workbench.name }}-storage
        persistentVolumeClaim:
          claimName: {{ .Values.workbench.name }}-storage
      - emptyDir:
          medium: Memory
        name: shm
      # - configMap:
      #     items:
      #     - key: ca-bundle.crt
      #       path: ca-bundle.crt
      #     name: workbench-trusted-ca-bundle
      #     optional: true
      #   name: trusted-ca
      # - configMap:
      #     name: pipeline-runtime-images
      #     optional: true
      #   name: runtime-images
      # - configMap:
      #     defaultMode: 420
      #     name: {{ .Values.workbench.name }}-kube-rbac-proxy-config
      #   name: kube-rbac-proxy-config
      # - name: kube-rbac-proxy-tls-certificates
      #   secret:
      #     defaultMode: 420
      #     secretName: {{ .Values.workbench.name }}-kube-rbac-proxy-tls
      # - name: elyra-dsp-details
