{{- with .Values.workbenches }}
{{- range . }}
---
apiVersion: kubeflow.org/v1
kind: Notebook
metadata:
  annotations:
    notebooks.opendatahub.io/inject-auth: "true"
    notebooks.opendatahub.io/last-image-selection: {{ .image | quote }}
    notebooks.opendatahub.io/last-image-version-git-commit-selection: {{ .lastImageVersionGitCommit | default "8e73cac" }}
    opendatahub.io/image-display-name: {{ .imageDisplayName | default "Jupyter | PyTorch | CUDA | Python 3.12" | quote }}
    opendatahub.io/connections: ""
    opendatahub.io/hardware-profile-name: {{ .hardwareProfile.name | quote }}
    opendatahub.io/hardware-profile-namespace: {{ .hardwareProfile.namespace | quote }}
    openshift.io/description: {{ .description | quote }}
    openshift.io/display-name: {{ .displayName | default .name }}
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: {{ .name }}
  namespace: {{ $.Values.dataScienceProjectNamespace }}
  labels:
    app: {{ .name }}
    opendatahub.io/dashboard: "true"
    opendatahub.io/odh-managed: "true"
    {{- if $.Values.distributedWorkloads.enabled }}
    kueue.x-k8s.io/queue-name: {{ $.Values.kueue.localQueueName | quote }}
    {{- end }}
spec:
  template:
    spec:
      affinity: {}
      containers:
      - env:
        - name: NOTEBOOK_ARGS
          value: |-
            --ServerApp.port=8888
            --ServerApp.token=''
            --ServerApp.password=''
            --ServerApp.base_url=/notebook/{{ $.Values.dataScienceProjectNamespace }}/{{ .name }}
            --ServerApp.quit_button=False
        - name: JUPYTER_IMAGE
          value: image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/{{ .image }}
        - name: REQUESTS_CA_BUNDLE
          value: /etc/pki/tls/custom-certs/ca-bundle.crt
        - name: SSL_CERT_FILE
          value: /etc/pki/tls/custom-certs/ca-bundle.crt
        - name: PIPELINES_SSL_SA_CERTS
          value: /etc/pki/tls/custom-certs/ca-bundle.crt
        - name: KF_PIPELINES_SSL_SA_CERTS
          value: /etc/pki/tls/custom-certs/ca-bundle.crt
        - name: GIT_SSL_CAINFO
          value: /etc/pki/tls/custom-certs/ca-bundle.crt
        - name: PIP_CERT
          value: /etc/pki/tls/custom-certs/ca-bundle.crt
        image: image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/{{ .image }}
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /notebook/{{ $.Values.dataScienceProjectNamespace }}/{{ .name }}/api
            port: notebook-port
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        name: {{ .name }}
        ports:
        - containerPort: 8888
          name: notebook-port
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /notebook/{{ $.Values.dataScienceProjectNamespace }}/{{ .name }}/api
            port: notebook-port
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: '{{ .resources.limits.cpu }}'
            memory: {{ .resources.limits.memory }}
            {{- if .resources.limits.nvidiaGpu }}
            nvidia.com/gpu: '{{ .resources.limits.nvidiaGpu }}'
            {{- end }}
          requests:
            cpu: '{{ .resources.requests.cpu }}'
            memory: {{ .resources.requests.memory }}
            {{- if .resources.requests.nvidiaGpu }}
            nvidia.com/gpu: '{{ .resources.requests.nvidiaGpu }}'
            {{- end }}
        volumeMounts:
        - mountPath: /opt/app-root/src/
          name: {{ .name }}-storage
        - mountPath: /dev/shm
          name: shm
        - mountPath: /etc/pki/tls/custom-certs/ca-bundle.crt
          name: trusted-ca
          readOnly: true
          subPath: ca-bundle.crt
        - mountPath: /opt/app-root/pipeline-runtimes/
          name: runtime-images
        - mountPath: /opt/app-root/runtimes	
          name: elyra-dsp-details
        workingDir: /opt/app-root/src
      enableServiceLinks: false
      serviceAccountName: {{ .name }}
      volumes:
      - name: {{ .name }}-storage
        persistentVolumeClaim:
          claimName: {{ .name }}-storage
      - emptyDir:
          medium: Memory
        name: shm
      - configMap:
          items:
          - key: ca-bundle.crt
            path: ca-bundle.crt
          name: workbench-trusted-ca-bundle
          optional: true
        name: trusted-ca
      - configMap:
          name: pipeline-runtime-images
          optional: true
        name: runtime-images
      # - configMap:
      #     defaultMode: 420
      #     name: {{ .name }}-kube-rbac-proxy-config
      #   name: kube-rbac-proxy-config
      - name: kube-rbac-proxy-tls-certificates
        secret:
          defaultMode: 420
          secretName: {{ .name }}-kube-rbac-proxy-tls
      - name: elyra-dsp-details
{{- end }}
{{- end }}
