{{- if .Values.pipelinesConnection.storageBackendODF }}
---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: {{ .Values.pipelinesConnection.secretName }}
  namespace: {{ .Values.dataScienceProjectNamespace }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  generateBucketName: {{ .Values.pipelinesConnection.secretName }}
  storageClassName: openshift-storage.noobaa.io
{{- end }}
