{{- if .Values.storageBackendODF }}
---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: odf-connection-pipelines
  namespace: {{ .Values.dataScienceProjectNamespace }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  generateBucketName: odf-connection-pipelines
  storageClassName: openshift-storage.noobaa.io
{{- end }}
