---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: llama-stack-playground
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: llama-stack-playground
    app.kubernetes.io/version: "latest"