{{- if .Values.clusterDomain }}
---
apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: {{ .Release.Namespace }}-attu
spec:
  href: "https://attu-{{ .Release.Namespace }}.apps.{{ .Values.clusterDomain }}"
  location: ApplicationMenu
  text: "Milvus | Attu"
  applicationMenu:
    section: OpenShift Self Managed Services
    imageURL: "https://images.crunchbase.com/image/upload/c_pad,h_170,w_170,f_auto,b_white,q_auto:eco,dpr_1/qa7uilyathgvb36hsfrf"
{{- end }}
