{{- if .Values.distributedWorkloads.enabled }}
---
#The Kueue ResourceFlavor object describes the resource variations that are available in a cluster.
apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: default-flavor
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  tolerations:
  - effect: NoSchedule
    operator: Exists
    key: nvidia.com/gpu
{{- end }}
