{{- if and .Values.modelsAsService.enabled }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: models-as-a-service-gw
  namespace: openshift-ingress
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "0"
spec:
  isCA: false
  commonName: "models-as-a-service.apps.{{ .Values.global.clusterDomain }}"
  dnsNames:
  - "models-as-a-service.apps.{{ .Values.global.clusterDomain }}"
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
    group: cert-manager.io
  secretName: maas-gw-service-tls
{{- end }}
