{{- if and .Values.modelsAsService.enabled (eq .Values.modelsAsService.exposeType "loadbalancer") }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: maas-gw
  namespace: openshift-ingress
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "0"
spec:
  isCA: false
  commonName: "maas.apps.{{ .Values.global.clusterDomain }}"
  dnsNames:
  - "maas.apps.{{ .Values.global.clusterDomain }}"
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
    group: cert-manager.io
  secretName: maas-gw-service-tls
{{- end }}
