{{- if and .Values.modelsAsService.enabled (eq .Values.modelsAsService.exposeType "loadbalancer") }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: maas-service-override
  namespace: openshift-ingress
  annotations:
    argocd.argoproj.io/sync-wave: "9"
data:
  service: |
    spec:
      type: LoadBalancer
{{- end }}
