{{- if and .Values.modelsAsService.enabled }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: maas
  namespace: openshift-ingress
  annotations:
    argocd.argoproj.io/sync-wave: "12"
    router.openshift.io/service-ca-certificate: "true"
spec:
  host: maas.apps.{{ .Values.global.clusterDomain }}
  to:
    kind: Service
    name: maas-default-gateway-maas-default-gateway
    weight: 100
  port:
    targetPort: 443
  tls:
    termination: reencrypt
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
{{- end }}
