{{- if and .Values.modelsAsService.enabled }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: models-as-a-service
  namespace: openshift-ingress
  annotations:
    argocd.argoproj.io/sync-wave: "12"
spec:
  host: models-as-a-service.apps.{{ .Values.global.clusterDomain }}
  to:
    kind: Service
    name: maas-default-gateway-maas-default-gateway
    weight: 100
  port:
    targetPort: 443
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: Redirect
{{- end }}
