{{- if $.Values.featureStore.enabled }}
{{- range $.Values.featureStore.examples }}
{{- if .enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: feast-apply-job
  namespace: {{ .namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "11"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: feast-apply-job
subjects:
- kind: ServiceAccount
  name: feast-apply-job
  namespace: {{ .namespace }}
{{- end }}
{{- end }}
{{- end }}
