{{- if and $.Values.featureStore.enabled $.Values.featureStore.examples }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: feast-apply-job
  namespace: {{ $.Values.featureStore.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "11"
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
{{- end }}
