{{- if $.Values.featureStore.enabled }}
{{- range $.Values.featureStore.examples }}
{{- if .enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: feast-apply-job
  namespace: {{ .namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "11"
{{- end }}
{{- end }}
{{- end }}
