---
{{ if and .Values.llm_d.enabled .Values.llm_d.ocpRouteGateway.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: openshift-ai-inference-ocproute
  namespace: openshift-ingress
  annotations:
    argocd.argoproj.io/sync-wave: "12"
spec:
  host: inference-gateway-route.apps.{{ .Values.global.clusterDomain }}
  port:
    targetPort: http
  to:
    kind: Service
    name: openshift-ai-inference-ocproute-openshift-ai-inference-ocproute
    weight: 100
  wildcardPolicy: None
{{ end }}
