---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:

  - deployment-minio.yaml
  - pvc-minio.yaml
  - secret-minio.yaml
  - svc-minio.yaml
  - route-minio-api.yaml
  - route-minio-ui.yaml
