---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-jobset-operator
  namespace: openshift-jobset-operator
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  targetNamespaces:
  - openshift-jobset-operator
  upgradeStrategy: Default
