{{- if and .Values.modelRegistry.enabled .Values.modelRegistry.mysql.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.modelRegistry.mysql.name }}-persistent-storage
  namespace: {{ .Values.modelRegistry.mysql.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.modelRegistry.mysql.persistence.size }}
{{- end }}
