{{- if and .Values.modelRegistry.enabled .Values.modelRegistry.mysql.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.modelRegistry.mysql.name }}
  namespace: {{ .Values.modelRegistry.mysql.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
{{- end }}
