---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-nfd
  namespace: openshift-nfd
  annotations:
    argocd.argoproj.io/sync-wave: "-05"
spec:
  targetNamespaces:
  - openshift-nfd