---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: authorino-operator
  namespace: openshift-operators
  annotations:
    argocd.argoproj.io/sync-wave: "-05"
spec:
  # channel: tech-preview-v1 # For OCP < 4.16
  channel: stable
  installPlanApproval: Automatic
  name: authorino-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
