{{- if .Values.modelTunning.enabled }}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: training-config
  namespace: {{ .Values.dataScienceProjectNamespace }}
data:
  config.json: |
    {
      "model_name_or_path": "bigscience/bloom-560m",
      "training_data_path": "/data/input/twitter_complaints.json",
      "output_dir": "/data/output/tuning/bloom-twitter",
      "save_model_dir": "/mnt/output/model",
      "num_train_epochs": 10.0,
      "per_device_train_batch_size": 4,
      "per_device_eval_batch_size": 4,
      "gradient_accumulation_steps": 4,
      "save_strategy": "no",
      "learning_rate": 1e-05,
      "weight_decay": 0.0,
      "lr_scheduler_type": "cosine",
      "include_tokens_per_second": true,
      "response_template": "\n### Label:",
      "dataset_text_field": "output",
      "padding_free": ["huggingface"],
      "multipack": [16],
      "use_flash_attn": false
      "peft_method": "lora",
      "lora_r": 8,
      "lora_alpha": 8,
      "lora_dropout": 0.1,
      "bias": "none",
      "target_modules": ["all-linear"]
    }
{{- end }}
